// Code generated by tools/gen_allowlist.py from crystaldba/postgres-mcp
// (src/postgres_mcp/sql/safe_sql.py). DO NOT EDIT BY HAND.

package safesql

// allowedStmts are the top-level statement types the server will run.
// Source: upstream SafeSqlDriver.ALLOWED_STMT_TYPES.
var allowedStmts = newSet(
	"ClosePortalStmt", "CreateExtensionStmt", "DeallocateStmt", "DeclareCursorStmt",
	"ExplainStmt", "FetchStmt", "PrepareStmt", "SelectStmt", "VacuumStmt", "VariableShowStmt",
)

// allowedNodes are the AST node types permitted anywhere inside those statements.
// Source: upstream SafeSqlDriver.ALLOWED_NODE_TYPES minus its statement types.
// Upstream stores the union, so the walk accepts allowedNodes | allowedStmts.
var allowedNodes = newSet(
	"A_ArrayExpr", "A_Const", "A_Expr", "A_Indices", "A_Indirection", "A_Star", "Alias",
	"BitString", "BoolExpr", "Boolean", "BooleanTest", "CaseExpr", "CaseWhen", "CoalesceExpr",
	"CollateClause", "ColumnRef", "CommonTableExpr", "DefElem", "Float", "FromExpr", "FuncCall",
	"GroupingFunc", "GroupingSet", "Integer", "JoinExpr", "MinMaxExpr", "NamedArgExpr",
	"NotifyStmt", "NullTest", "ParamRef", "RangeFunction", "RangeSubselect", "RangeTableFunc",
	"RangeTableFuncCol", "RangeTableSample", "RangeVar", "RawStmt", "ResTarget", "RowCompareExpr",
	"RowExpr", "SQLValueFunction", "ScalarArrayOpExpr", "SortBy", "SortGroupClause", "String",
	"SubLink", "TableFunc", "TableSampleClause", "TargetEntry", "TypeCast", "TypeName",
	"WindowClause", "WindowDef", "WindowFunc", "WithClause",
)

// allowedFuncs is the function allowlist, matched on the unqualified name, so
// `pg_catalog.count` and `count` are the same entry.
// Source: upstream SafeSqlDriver.ALLOWED_FUNCTIONS.
var allowedFuncs = newSet(
	"abbrev", "abs", "acldefault", "aclexplode", "acos", "acosd", "acosh", "age", "any", "area",
	"array", "array_agg", "array_append", "array_cat", "array_dims", "array_fill", "array_length",
	"array_lower", "array_ndims", "array_position", "array_positions", "array_prepend",
	"array_remove", "array_replace", "array_sample", "array_shuffle", "array_to_json",
	"array_to_string", "array_to_tsvector", "array_upper", "ascii", "asin", "asind", "asinh",
	"atan", "atan2", "atan2d", "atand", "atanh", "avg", "bit_and", "bit_length", "bit_or", "bool",
	"bool_and", "bool_or", "broadcast", "btrim", "cardinality", "cast", "cbrt", "ceil", "ceiling",
	"center", "char_length", "character_length", "chr", "cidr_split", "clock_timestamp", "concat",
	"concat_ws", "convert", "convert_from", "convert_to", "cos", "cosd", "cosh", "cot", "cotd",
	"count", "crypt", "cube_distance", "cume_dist", "current_catalog", "current_database",
	"current_date", "current_query", "current_role", "current_schema", "current_schemas",
	"current_setting", "current_time", "current_timestamp", "current_user", "currval", "date",
	"date_part", "date_trunc", "decode", "degrees", "dense_rank", "diameter", "difference",
	"digest", "div", "dmetaphone", "earth_box", "earth_distance", "earth_to_ll", "encode",
	"encrypt", "enum_first", "enum_last", "enum_range", "erf", "erfc", "every", "exp", "extract",
	"factorial", "family", "first_value", "float4", "float8", "floor", "format", "format_type",
	"gcd", "gen_random_uuid", "gen_salt", "get_current_ts_config", "has_any_column_privilege",
	"has_column_privilege", "has_database_privilege", "has_foreign_data_wrapper_privilege",
	"has_function_privilege", "has_language_privilege", "has_parameter_privilege",
	"has_schema_privilege", "has_sequence_privilege", "has_server_privilege",
	"has_table_privilege", "has_tablespace_privilege", "has_type_privilege", "height", "hmac",
	"host", "hostmask", "hypopg_create_index", "hypopg_get_indexdef", "hypopg_hide_index",
	"hypopg_list_indexes", "hypopg_relation_size", "hypopg_reset", "hypopg_unhide_index",
	"icu_unicode_version", "inet_client_addr", "inet_client_port", "inet_merge",
	"inet_same_family", "inet_server_addr", "inet_server_port", "initcap", "int2", "int4", "int8",
	"interval", "isclosed", "isempty", "isfinite", "isopen", "json", "json_agg",
	"json_array_elements", "json_array_elements_text", "json_array_length", "json_build_array",
	"json_build_object", "json_each", "json_each_text", "json_extract_path",
	"json_extract_path_text", "json_object", "json_object_agg", "json_object_keys",
	"json_populate_record", "json_populate_recordset", "json_scalar", "json_serialize",
	"json_strip_nulls", "json_to_record", "json_to_recordset", "json_typeof", "jsonb_agg",
	"jsonb_array_elements", "jsonb_array_elements_text", "jsonb_array_length",
	"jsonb_build_array", "jsonb_build_object", "jsonb_each", "jsonb_each_text",
	"jsonb_extract_path", "jsonb_extract_path_text", "jsonb_insert", "jsonb_object",
	"jsonb_object_agg", "jsonb_object_keys", "jsonb_path_exists", "jsonb_path_exists_tz",
	"jsonb_path_match", "jsonb_path_match_tz", "jsonb_path_query", "jsonb_path_query_array",
	"jsonb_path_query_array_tz", "jsonb_path_query_first", "jsonb_path_query_first_tz",
	"jsonb_path_query_tz", "jsonb_populate_record", "jsonb_populate_record_valid",
	"jsonb_populate_recordset", "jsonb_pretty", "jsonb_set", "jsonb_set_lax", "jsonb_set_path",
	"jsonb_strip_nulls", "jsonb_to_record", "jsonb_to_recordset", "jsonb_typeof", "jsonbv_typeof",
	"justify_days", "justify_hours", "justify_interval", "lag", "last_value", "lastval", "lcm",
	"lead", "left", "length", "levenshtein", "ll_to_earth", "ln", "localtime", "localtimestamp",
	"log", "log10", "lower", "lower_inc", "lower_inf", "lpad", "ltrim", "macaddr8_set7bit",
	"make_date", "make_interval", "make_time", "make_timestamp", "make_timestamptz",
	"makeaclitem", "masklen", "max", "md5", "metaphone", "min", "min_scale", "mod", "mode",
	"netmask", "network", "normalize", "now", "npoints", "nth_value", "ntile", "numeric",
	"numnode", "octet_length", "overlay", "parse_ident", "pclose", "percent_rank",
	"percentile_cont", "percentile_disc", "pg_available_wal_summaries", "pg_backend_pid",
	"pg_basetype", "pg_blocking_pids", "pg_char_to_encoding", "pg_client_encoding",
	"pg_collation_is_visible", "pg_column_compression", "pg_column_size",
	"pg_column_toast_chunk_id", "pg_conf_load_time", "pg_control_checkpoint", "pg_control_init",
	"pg_control_recovery", "pg_control_system", "pg_conversion_is_visible", "pg_current_logfile",
	"pg_current_snapshot", "pg_current_xact_id", "pg_database_size", "pg_encoding_to_char",
	"pg_function_is_visible", "pg_get_catalog_foreign_keys", "pg_get_constraintdef",
	"pg_get_expr", "pg_get_function_arguments", "pg_get_function_identity_arguments",
	"pg_get_function_result", "pg_get_functiondef", "pg_get_indexdef", "pg_get_keywords",
	"pg_get_partkeydef", "pg_get_ruledef", "pg_get_serial_sequence", "pg_get_statisticsobjdef",
	"pg_get_triggerdef", "pg_get_userbyid", "pg_get_viewdef", "pg_get_wal_summarizer_state",
	"pg_has_role", "pg_index_column_has_property", "pg_index_has_property",
	"pg_indexam_has_property", "pg_indexes_size", "pg_input_error_info", "pg_input_is_valid",
	"pg_is_in_recovery", "pg_is_other_temp_schema", "pg_jit_available", "pg_listening_channels",
	"pg_my_temp_schema", "pg_notification_queue_usage", "pg_opclass_is_visible",
	"pg_operator_is_visible", "pg_opfamily_is_visible", "pg_options_to_table",
	"pg_postmaster_start_time", "pg_relation_filenode", "pg_relation_size",
	"pg_safe_snapshot_blocking_pids", "pg_settings_get_flags", "pg_size_bytes", "pg_size_pretty",
	"pg_snapshot_xip", "pg_statistics_obj_is_visible", "pg_table_is_visible", "pg_table_size",
	"pg_tablespace_databases", "pg_tablespace_location", "pg_tablespace_size",
	"pg_total_relation_size", "pg_trigger_depth", "pg_ts_config_is_visible",
	"pg_ts_dict_is_visible", "pg_ts_parser_is_visible", "pg_ts_template_is_visible",
	"pg_type_is_visible", "pg_typeof", "pg_wal_summary_contents", "pg_xact_commit_timestamp",
	"phraseto_tsquery", "pi", "plainto_tsquery", "popen", "position", "power", "querytree",
	"quote_ident", "quote_literal", "quote_nullable", "radians", "radius", "random",
	"random_normal", "range_merge", "rank", "regclass", "regexp_count", "regexp_instr",
	"regexp_like", "regexp_match", "regexp_matches", "regexp_replace", "regexp_split_to_array",
	"regexp_split_to_table", "regexp_substr", "repeat", "replace", "reverse", "right", "round",
	"row_number", "row_security_active", "row_to_json", "rpad", "rtrim", "scale", "session_user",
	"set_bit", "set_masklen", "setseed", "setweight", "show_limit", "show_trgm", "sign",
	"similarity", "sin", "sind", "sinh", "soundex", "split_part", "sqrt", "starts_with",
	"statement_timestamp", "strict_word_similarity", "string_agg", "string_to_array",
	"string_to_table", "strip", "strpos", "substr", "substring", "sum", "system_user", "tan",
	"tand", "tanh", "text", "time", "timeofday", "timestamp", "timestamptz", "timetz", "to_ascii",
	"to_bin", "to_char", "to_date", "to_hex", "to_json", "to_jsonb", "to_number", "to_oct",
	"to_regclass", "to_regcollation", "to_regnamespace", "to_regoper", "to_regoperator",
	"to_regproc", "to_regprocedure", "to_regrole", "to_regtype", "to_regtypemod", "to_timestamp",
	"to_tsquery", "to_tsvector", "transaction_timestamp", "translate", "trim", "trim_array",
	"trim_scale", "trunc", "ts_debug", "ts_delete", "ts_filter", "ts_headline", "ts_lexize",
	"ts_parse", "ts_rank", "ts_rank_cd", "ts_rewrite", "ts_stat", "ts_token_type",
	"tsvector_to_array", "unicode_assigned", "unicode_version", "unistr", "unnest", "upper",
	"upper_inc", "upper_inf", "user", "version", "websearch_to_tsquery", "width", "width_bucket",
	"word_similarity", "xml", "xml_is_well_formed", "xml_is_well_formed_content",
	"xml_is_well_formed_document", "xmlagg", "xmlcomment", "xmlconcat", "xmlelement", "xmlexists",
	"xmlforest", "xmlnamespaces", "xmlpi", "xmlroot", "xmltable", "xpath", "xpath_exists",
)

// allowedExtensions is the CREATE EXTENSION allowlist.
// Source: upstream SafeSqlDriver.ALLOWED_EXTENSIONS.
var allowedExtensions = newSet(
	"address_standardizer", "address_standardizer_data_us", "adminpack", "age", "amcheck",
	"auto_explain", "aws_commons", "aws_s3", "bloom", "btree_gin", "btree_gist", "chkpass",
	"citext", "citus", "cube", "dblink", "dict_int", "dict_xsyn", "earthdistance", "file_fdw",
	"fuzzystrmatch", "h3", "hstore", "hypopg", "intagg", "intarray", "ip4r", "isn", "lo", "ltree",
	"moddatetime", "mongo_fdw", "mysql_fdw", "oracle_fdw", "orafce", "pg_bigm", "pg_buffercache",
	"pg_cron", "pg_freespacemap", "pg_fuzzystrmatch", "pg_graphql", "pg_hint_plan", "pg_ivm",
	"pg_net", "pg_partman", "pg_partman_bgw", "pg_prewarm", "pg_qualstats", "pg_rational",
	"pg_repack", "pg_roaringbitmap", "pg_stat_kcache", "pg_stat_monitor", "pg_stat_statements",
	"pg_tle", "pg_track_settings", "pg_trgm", "pg_variables", "pg_visibility", "pg_wait_sampling",
	"pg_walinspect", "pgaudit", "pgcrypto", "pgjwt", "pglogical", "pgmq", "pgpool_adm", "pgq",
	"pgrouting", "pgrowlocks", "pgsphere", "pgstattuple", "pgtap", "pgvector", "pljava", "plperl",
	"plperlu", "plpgsql", "plpython", "plpython3u", "plrust", "pltcl", "pltclu", "plv8",
	"postgis", "postgis_raster", "postgis_sfcgal", "postgis_tiger_geocoder", "postgis_topology",
	"postgres_fdw", "q3c", "rdkit", "rum", "seg", "semver", "spi", "sslinfo", "tablefunc",
	"tds_fdw", "timescaledb", "tsm_system_rows", "tsm_system_time", "tsvector2", "unaccent",
	"uuid-ossp", "vector", "wal2json", "xml2", "zhparser",
)

// alwaysAllowed are protobuf-only node types with no pglast equivalent, so they
// are absent from the transcribed sets above. `Node` is the oneof wrapper that
// carries every concrete message; it has no fields of its own beyond that
// wrapper, so the walk passes it through and checks the message it holds.
var alwaysAllowed = newSet(
	"Node",
)
