// Package safesql decides whether a SQL statement is safe for a read-only MCP
// server to run.
//
// The rules are transcribed from crystaldba/postgres-mcp, which enforces them
// with a hand-written visitor over pglast's AST. This port walks the protobuf
// tree generically instead, so the cost is one map lookup per node rather than
// one visitor method per node type. See allowlist_gen.go, generated by
// tools/gen_allowlist.py.
//
// Validate is one of four layers; the others live in internal/pg and are
// enforced by Postgres itself:
//
//  1. every pooled connection runs with default_transaction_read_only=on
//  2. pgx uses the extended query protocol, where Postgres rejects more than
//     one statement per Parse message
//  3. Validate's statement-type allowlist
//  4. Validate's node and function allowlists
package safesql

import (
	"fmt"
	"strings"

	pg_query "github.com/pganalyze/pg_query_go/v6"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Validate reports why sql is unsafe to run, or nil if it is safe.
//
// It is an allowlist, not a denylist: anything the parser produces that is not
// explicitly permitted is rejected, so a Postgres version that grows a new node
// type fails closed.
func Validate(sql string) error {
	tree, err := pg_query.Parse(sql)
	if err != nil {
		return fmt.Errorf("failed to parse SQL statement: %w", err)
	}
	// One statement only. The extended query protocol would reject this too, but
	// failing here means the error names the real problem.
	if n := len(tree.GetStmts()); n != 1 {
		return fmt.Errorf("expected exactly 1 statement, got %d", n)
	}

	stmt := tree.GetStmts()[0]
	if stmt.GetStmt() == nil {
		return fmt.Errorf("statement is empty")
	}
	if name := nodeName(concrete(stmt.GetStmt().ProtoReflect())); !allowedStmts[name] {
		return fmt.Errorf("statement type %s is not allowed", name)
	}
	return (&walker{}).walk(stmt.ProtoReflect())
}

type walker struct{}

func (w *walker) walk(m protoreflect.Message) error {
	name := nodeName(m)
	// Upstream's ALLOWED_NODE_TYPES is the union of its statement types and its
	// node types, so a nested SELECT is legal too. alwaysAllowed covers the
	// protobuf-only wrapper.
	if !allowedNodes[name] && !allowedStmts[name] && !alwaysAllowed[name] && !goPortAdditions[name] {
		return fmt.Errorf("node type %s is not allowed", name)
	}
	if err := specialCase(m); err != nil {
		return err
	}

	var err error
	m.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if err != nil {
			return false
		}
		switch {
		case fd.IsList():
			list := v.List()
			for i := range list.Len() {
				if fd.Message() != nil {
					if err = w.walk(list.Get(i).Message()); err != nil {
						return false
					}
				}
			}
		case fd.Message() != nil:
			err = w.walk(v.Message())
		}
		return err == nil
	})
	return err
}

// specialCase covers the four checks that a node-name allowlist cannot express.
func specialCase(m protoreflect.Message) error {
	switch n := m.Interface().(type) {
	case *pg_query.SelectStmt:
		// LockingClause is already absent from the allowlist, so the walk would
		// reject it; this only makes the error legible.
		if len(n.GetLockingClause()) > 0 {
			return fmt.Errorf("locking clause (FOR UPDATE/SHARE) is not allowed")
		}
	case *pg_query.FuncCall:
		name, err := funcName(n)
		if err != nil {
			return err
		}
		if !allowedFuncs[name] {
			return fmt.Errorf("function %s is not allowed", name)
		}
	case *pg_query.A_Expr:
		// A parameterised LIKE pattern is how a caller smuggles in a scan the
		// statement author never intended, so the pattern must be a literal.
		if k := n.GetKind(); k == pg_query.A_Expr_Kind_AEXPR_LIKE || k == pg_query.A_Expr_Kind_AEXPR_ILIKE {
			if !isAConst(n.GetRexpr()) {
				return fmt.Errorf("LIKE pattern must be a constant string")
			}
		}
	case *pg_query.ExplainStmt:
		for _, opt := range n.GetOptions() {
			if d, ok := opt.GetNode().(*pg_query.Node_DefElem); ok && strings.EqualFold(d.DefElem.GetDefname(), "analyze") {
				// EXPLAIN ANALYZE executes the statement, which is not read-only.
				return fmt.Errorf("EXPLAIN ANALYZE is not supported")
			}
		}
	case *pg_query.CreateExtensionStmt:
		if ext := strings.ToLower(n.GetExtname()); !allowedExtensions[ext] {
			return fmt.Errorf("CREATE EXTENSION %s is not supported", n.GetExtname())
		}
	}
	return nil
}

// funcName flattens FuncCall.funcname to a dotted lowercase name and drops a
// pg_catalog qualifier, so `pg_catalog.count` and `count` hit the same entry.
func funcName(fc *pg_query.FuncCall) (string, error) {
	parts := make([]string, 0, len(fc.GetFuncname()))
	for _, part := range fc.GetFuncname() {
		s := part.GetString_()
		if s == nil {
			return "", fmt.Errorf("cannot resolve function name")
		}
		parts = append(parts, strings.ToLower(s.GetSval()))
	}
	name := strings.Join(parts, ".")
	if after, ok := strings.CutPrefix(name, "pg_catalog."); ok {
		name = after
	}
	return name, nil
}

func isAConst(n *pg_query.Node) bool {
	if n == nil {
		return false
	}
	_, ok := n.GetNode().(*pg_query.Node_AConst)
	return ok
}

// nodeName strips the `pg_query.` package prefix from a descriptor name.
func nodeName(m protoreflect.Message) string {
	full := string(m.Descriptor().FullName())
	if _, after, ok := strings.Cut(full, "."); ok {
		return after
	}
	return full
}

// concrete unwraps the oneof holder that the protobuf tree puts in front of every
// node, so `Node{SelectStmt}` reports as SelectStmt. The field is found by
// reflection rather than by name so this survives a pg_query_go upgrade.
func concrete(m protoreflect.Message) protoreflect.Message {
	if _, ok := m.Interface().(*pg_query.Node); !ok {
		return m
	}
	fields := m.Descriptor().Fields()
	for i := range fields.Len() {
		if fd := fields.Get(i); m.Has(fd) && fd.Message() != nil {
			return m.Get(fd).Message()
		}
	}
	return m
}

// goPortAdditions are node types this port allows that upstream does not. They
// live here rather than in the generated file so that diffing the generated
// allowlist against upstream stays a meaningful review.
//
// VacuumStmt is on upstream's statement allowlist but VacuumRelation is missing
// from its node allowlist, so upstream rejects `ANALYZE t` and `VACUUM t`. Its
// intent is clearly to allow both, so this port allows the one missing node.
var goPortAdditions = newSet("VacuumRelation")

func newSet(items ...string) map[string]bool {
	set := make(map[string]bool, len(items))
	for _, item := range items {
		set[item] = true
	}
	return set
}
