"""Transcribe crystaldba/postgres-mcp safe-SQL allowlists into Go source.

Run:  python3 tools/gen_allowlist.py ../postgres-mcp/src/postgres_mcp/sql/safe_sql.py > internal/safesql/allowlist_gen.go

Kept in the repo on purpose: the allowlist is 250+ identifiers copied from the
Python project, and hand-editing it is how it silently rots.
"""

import re
import sys

SRC = (
    sys.argv[1]
    if len(sys.argv) > 1
    else "../postgres-mcp/src/postgres_mcp/sql/safe_sql.py"
)
src = open(SRC).read()

# The protobuf tree adds one node type pglast has no equivalent for: `Node`, the
# oneof wrapper that carries every concrete statement/expression message. pglast
# models the same thing with Python classes, so upstream never sees it. The list is
# derived, not hardcoded, so it self-corrects if upstream ever adds a value node.
WRAPPER_CANDIDATES = ["Node", "String", "Integer", "Float", "Boolean", "BitString"]


def block(name):
    """Return the {...} body of `NAME ... = {` up to the matching brace."""
    m = re.search(rf"^\s*{name}[^=]*=\s*[^{{]*\{{", src, re.M)
    if not m:
        raise SystemExit(f"{name}: not found")
    i = m.end() - 1
    depth = 0
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[i + 1 : j]
    raise SystemExit(f"{name}: unbalanced braces")


def strip_comments(s):
    return re.sub(r"\s+", " ", re.sub(r"#[^\n]*", "", s))


def idents(name):
    return re.findall(r"[A-Za-z_][A-Za-z0-9_]*", strip_comments(block(name)))


def strings(name):
    return re.findall(r'"([^"]+)"', strip_comments(block(name)))


def wrap(items):
    line, lines = "\t", []
    for it in items:
        piece = f'"{it}",'
        if len(line) + len(piece) + 1 > 96:
            lines.append(line.rstrip())
            line = "\t"
        line += piece + " "
    if line.strip():
        lines.append(line.rstrip())
    return "\n".join(lines)


stmts = sorted(set(idents("ALLOWED_STMT_TYPES")))
nodes = sorted(set(idents("ALLOWED_NODE_TYPES")) - set(stmts))
funcs = sorted(set(strings("ALLOWED_FUNCTIONS")))
exts = sorted(set(strings("ALLOWED_EXTENSIONS")))

wrappers = [n for n in WRAPPER_CANDIDATES if n not in stmts + nodes]
print(f"// note: protobuf-only node types: {wrappers}", file=sys.stderr)

print(
    f"""// Code generated by tools/gen_allowlist.py from crystaldba/postgres-mcp
// (src/postgres_mcp/sql/safe_sql.py). DO NOT EDIT BY HAND.

package safesql

// allowedStmts are the top-level statement types the server will run.
// Source: upstream SafeSqlDriver.ALLOWED_STMT_TYPES.
var allowedStmts = newSet(
{wrap(stmts)}
)

// allowedNodes are the AST node types permitted anywhere inside those statements.
// Source: upstream SafeSqlDriver.ALLOWED_NODE_TYPES minus its statement types.
// Upstream stores the union, so the walk accepts allowedNodes | allowedStmts.
var allowedNodes = newSet(
{wrap(nodes)}
)

// allowedFuncs is the function allowlist, matched on the unqualified name, so
// `pg_catalog.count` and `count` are the same entry.
// Source: upstream SafeSqlDriver.ALLOWED_FUNCTIONS.
var allowedFuncs = newSet(
{wrap(funcs)}
)

// allowedExtensions is the CREATE EXTENSION allowlist.
// Source: upstream SafeSqlDriver.ALLOWED_EXTENSIONS.
var allowedExtensions = newSet(
{wrap(exts)}
)

// alwaysAllowed are protobuf-only node types with no pglast equivalent, so they
// are absent from the transcribed sets above. `Node` is the oneof wrapper that
// carries every concrete message; it has no fields of its own beyond that
// wrapper, so the walk passes it through and checks the message it holds.
var alwaysAllowed = newSet(
{wrap(wrappers)}
)
"""
)
